# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-05-31 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='RegistredUser',
        ),
    ]
