# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-05-31 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0003_auto_20210531_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='registreduser',
            name='username',
            field=models.CharField(default='uggla', max_length=152),
        ),
    ]
