# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-05-31 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0004_registreduser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registreduser',
            name='username',
            field=models.CharField(default='uggla', max_length=15),
        ),
    ]
