# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-05-31 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0005_auto_20210531_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registreduser',
            name='username',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
